### PR TITLE
Add G4 family support

### LINKED ISSUE #6: STM32G474xx support
Hi,
I was trying to port the ST USBPD library to work with Arduino but discovered your project.
However, it seems you only support STM32G431xx. This part is not so different from the G474. I am working on developing some USBPD applications so I am using the G474RE nucleo along with the SNK1M1 shield, which should be compatible with your library (it just connects the CC lines to a dedicated USB port, along with a MOSFET for shutting off Vbus downstream of the port).
When building a bare UCPD project from CubeMX the connection to source works fine. With this library, I don't seem to get any response from the sink when the source advertises PDOs. Do you have any suggestions to debug this? 
I have added define flags at all locations where there are guards for the G431xx to also include G474xx.

### PR DESCRIPTION
**Pull request by VIPQualityPost**
Add support for other G4 Nucleo boards (G431RB, G474RE, G491RE)
Add support for building "standard" G4 family (G474xx, G491xx)
Use ARDUINO_NUCLEO defines to clarify pins used on dev kits for CC pins.
Closes #6.

### CODE REVIEW

**Comment by VIPQualityPost** [comment]
I didn't add all details for G491xx, because I don't have hardware to test, but I checked and it should not have any pin differences from the G474xx configuration. I'm not sure whether to leave out entirely or just add complete support, or something in between so that people can try it.

**Comment by manuelbl** [comment]
Thanks for the PR. I have an additional Nucleo G4 family board coming my way and will test it later this week.

**Comment by VIPQualityPost** [comment]
Thanks!
I have some G0 boards that I will also try to add some support for those as well. 
I am still working to understand the PD protocol a bit better. I would eventually like to add support for SRC role.
Can I ask how you discovered the issue with SOP markers earlier? You cannot debug this with print statements, right? Do you just follow along in the debugger and have a strong understanding of the protocol?

**Comment by manuelbl** [comment]
I used PlatformIO and ran the [test/VoltageChange](https://github.com/manuelbl/usb-pd-arduino/tree/main/test/VoltageChange) project in debug mode.

Since the timing is critical, it's not really possible to stop at a breakpoint and continue. The power source will have given up by that time. It's more of a one-shot debugging. If a breakpoint is hit, you can examine the variable values and continue for a few steps to see what branches are taken. But then you have to set different breakpoints and start over.

Using that technique, I tried to understand why it wouldn't set a voltage different from 5V: the break point (the function for setting it) was never hit. That way it went backwards to the event dispatch, GoodCRC transmitting until I finally discovered that the log had been saying "INV" instead of "SOP" all the time. From there is was easy.

**Comment by manuelbl** [comment]
The Nucleo boards have arrived: a Nucleo G474RE, a Nucleo G071RB and the SNK1M1 shield. I've extended the library to cover the latter two as well, in addition to the G474RE you have already provided.

The code is still a bit too Nucelo specific. I need to go over the `#if`s again and make it more generic such that it works for generic boards with the same MCUs as well.

**Comment by VIPQualityPost** [comment]
There is available the `ARDUINO_GENERIC_G****` build flag, but then this requires needing both Nucleo and Generic defines.

Are you sure that actually it's required to set the pin with pinMode before doing the GPIO configuration with LL driver? I haven't checked but I don't think the framework needs to use this, in which case we can just use the `STM32G4xx` defines for configuring pins, and remove the pinMode stuff entirely.

**Comment by VIPQualityPost** [comment]
I was thinking - usually when I am working with stm32duino I just use the "real" names e.g. PB4 rather than "Arduino-fied" names. And it seems that the framework is doing this anyway when you use any Arduino name, it will call something like 
```void ArduinoPinToHAL(uint32_t APin, uint32_t* HALPin, GPIO_TypeDef** HALPort)
{
	uint32_t Pin = digitalPinToPinName(APin);
	*HALPort = get_GPIO_Port(STM_PORT(Pin));
	*HALPin  = STM_LL_GPIO_PIN(Pin);
}
```
anyway, so I think maybe we can just skip this and directly use pinMode(PB4, OUTPUT) rather than "D10" or specific numbers that depend on layout but are unchanged on the silicon.

**Comment by manuelbl** [comment]
If that works, it would be very helpful. It would basically cover entire STM32 families.

**Comment by VIPQualityPost** [comment]
I was going to make the changes today, but discovered you already addressed it! Thanks!
Here is something I built with your library, doing motor control over single wire (USB power + data): https://youtu.be/Vx6fxW4_j_4

**Comment by manuelbl** [comment]
That looks great! Thanks for sharing.

**Pull request merged**
